name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.3.0
  device_apps: ^2.2.0
  app_settings: ^6.1.1
  permission_handler: ^12.0.0
  flutter_time_picker_spinner: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.3.0
  lucide_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true